version: '3.9'

services:
  db:
    image: postgres:15
    container_name: mini_app_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      # POSTGRES_DB: base
    ports:
      - "8489:5432"
    restart: always