version: '3.9'

services:
  db:
    image: postgres:15
    container_name: mini_app_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "8489:5432"
    restart: always
    volumes:
      - /home/:/home/ 
    command: >
      sh -c "chown postgres:postgres /home/ &&
             chmod 700 /home/ &&
             docker-entrypoint.sh postgres"
